spring:
  application:
    name: mailgun
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}
  profiles:
    active: local

config:
  url :